### ISSUE TITLE
Instructions don't work if ROS has never been used before

### ISSUE THREAD

**Issue by emmanuelkring** [RVMI/rvmi_workspace_setup#3]
I tried to follow the setup instructions, but failed saying
```
The catkin CMake module was not found
```
I think it's due to ROS not having been used at all with this account, so the catkin config says this
```
Profile:                     default
Extending:                   None
Workspace:                   /home/kring/rvmi_ws
```
Adding an additional command 
```
catkin config --extend /opt/ros/melodic
```
before the first build fixed it. You might want to consider adding that one to your documentation. (I will not just change your docs in the wiki and there aren't pull requests for the wiki)

**Comment by frovida** [comment]
I guess this happens if you don't source ros setup.bash? I updated the install steps, hopefully this is covered now
