### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by emmanuelkring** [RVMI/rvmi_workspace_setup#6]
In the wiki, the line
```
cd ~ mkdir -p rvmi_ws/src && cd rvmi_ws
```
results in
```
bash: cd: too many arguments
```
there should be a semicolon after the tilde

```
cd ~; mkdir -p rvmi_ws/src && cd rvmi_ws
```

**Comment by frovida** [comment]
Should have been on a different line, always forget the 2spaces at the end, fixed
